name: binder-voila
channels:
  - conda-forge
dependencies:
  - python=3.11
  - voila
  - ipywidgets
  - numpy
  - matplotlib
  - scipy
  - pandas
  # ajoute ici les libs dont tes notebooks ont besoin@
